#!/bin/bash

PACKER=/mnt/c/HashiCorp/Packer/bin/packer.exe

PWD=$(basename `pwd`)
if [ $PWD != "packer" ]
then
	echo "ERROR: run in packer parent dir"
	exit
fi

clear

if [ $# -ne 1 ]
then
	echo "USAGE: `basename $0` <validate|format|build|force>" ; echo
	exit
fi

[ -d packer_cache ] && rm -rf packer_cache

if [[ $1 =~ (validate|build|force) ]]
then
	echo Preparing INFO
	read -p "Enter Author Name: " AUTHOR
	sed -i 's/AUTHOR/'"$AUTHOR"'/g' ./info.json 
	echo
	echo Preparing HCL
        ./update-gold-md5
	echo
fi

case "$1" in

   validate) echo Validating HCL
      echo
      $PACKER validate templates/rhel8/gold.pkr.hcl
      echo
      echo Cleaning HCL
      ./revert-md5-placeholder
      echo
      echo Cleaning INFO
      sed -i 's/"Author.*$/"Author": "AUTHOR",/g' info.json
      exit
      ;;
   format) echo Formating HCL
      echo
      $PACKER fmt templates/rhel8/gold.pkr.hcl
      echo
      exit
      ;;
   build) echo Building HCL
      echo
      $PACKER build -color=true templates/rhel8/gold.pkr.hcl
      echo
      echo Cleaning HCL
      ./revert-md5-placeholder
      echo
      echo Cleaning INFO
      sed -i 's/"Author.*$/"Author": "AUTHOR",/g' info.json
      echo
      exit
      ;;
   force) echo Force Building HCL
      echo
      rm -rf /mnt/d/Virtual_Machines/rhel8/
      $PACKER build -force -color=true templates/rhel8/gold.pkr.hcl
      echo
      echo Cleaning HCL
      ./revert-md5-placeholder
      echo
      echo Cleaning INFO
      sed -i 's/"Author.*$/"Author": "AUTHOR",/g' info.json
      echo
      exit
      ;;
   *) echo No Valid Action Seen
      echo
      exit
      ;;
esac
