---

  - name: Mount ISO
    ansible.posix.mount:
      path: /mnt/
      src: /home/vagrant/VBoxGuestAdditions.iso
      fstype: iso9660
      opts: ro
      state: mounted

  - name: Install VBoxLinuxAdditions
    shell: sudo /mnt/VBoxLinuxAdditions.run

 
